"""Factor SignalEngine template for Strategy Development Manager.

Generated by sdm_register for factor: {FACTOR_NAME}
Source: {SOURCE_PAPER}
Formula: {FORMULA_LATEX}

This template satisfies the backtest runner SignalEngine contract:
- Class named SignalEngine
- No-arg constructor (all params have defaults)
- generate(data_map) -> dict[str, pd.Series]
"""

from __future__ import annotations

import pandas as pd


class SignalEngine:
    """Cross-sectional factor signal engine.

    Computes factor values and converts to position signals.
    """

    def __init__(
        self,
        lookback: int = 20,
        neutralize: bool = True,
    ) -> None:
        self.lookback = lookback
        self.neutralize = neutralize

    def generate(self, data_map: dict[str, pd.DataFrame]) -> dict[str, pd.Series]:
        """Generate factor-based position signals.

        Args:
            data_map: symbol -> OHLCV DataFrame with columns
                      [open, high, low, close, volume] indexed by date.

        Returns:
            symbol -> pd.Series of target signals (float, clipped to [-1, 1]).
        """
        signals: dict[str, pd.Series] = {}

        # Step 1: Compute raw factor values for each symbol
        factor_values: dict[str, pd.Series] = {}
        for symbol, df in data_map.items():
            # TODO: Replace with actual factor formula from paper
            # Example: 12-month momentum (Jegadeesh & Titman 1993)
            factor_values[symbol] = (
                df["close"].pct_change(self.lookback)
            )

        # Step 2: Cross-sectional ranking
        all_dates = sorted(
            {date for fv in factor_values.values() for date in fv.index}
        )
        for date in all_dates:
            cross_section = {
                sym: fv.loc[date]
                for sym, fv in factor_values.items()
                if date in fv.index and pd.notna(fv.loc[date])
            }
            if len(cross_section) < 5:
                continue

            # Rank-based signal: top quintile = +1, bottom quintile = -1
            ranked = pd.Series(cross_section).rank(pct=True)
            for symbol, rank in ranked.items():
                if symbol not in signals:
                    signals[symbol] = pd.Series(dtype=float)
                # Linear mapping: rank 0 -> -1, rank 1 -> +1
                signal_val = 2.0 * rank - 1.0
                signals[symbol] = pd.concat([
                    signals[symbol],
                    pd.Series([signal_val], index=[date]),
                ])

        # Step 3: Clip signals to [-1, 1]
        for symbol in signals:
            signals[symbol] = signals[symbol].clip(-1.0, 1.0)

        return signals
